version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.modelmapper.extensions:modelmapper-spring
    versions:
    - 2.3.9
    - 2.4.0
    - 2.4.1
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-cache
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-data-jpa
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
    - 5.4.29.Final
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
